#
# 'demo_checksum' DSP example component makefile
#

include ../../install.mk
include ../../../scp.mk


TARGET_BASENAME=demo_checksum

HDR= demo_checksum.h

OBJ= \
	demo_checksum.o64


OPTFLAGS+= $(OPTFLAGS_NONE)
#OPTFLAGS+= $(OPTFLAGS_SPEED)
#OPTFLAGS+= $(OPTFLAGS_SIZE)


include ../../build_area2.mk

include ../../build.mk


.PHONY: scp
scp: bin
	$(SCP) \
		$(TARGET_BASENAME)*.out \
		$(SCP_USER)@$(SCP_HOST):$(SCP_PATH)
