
TARGET=c64_load

CC=gcc
RM=rm -f


CFLAGS= -Wall

CFGFLAGS= -DHAVE_OS_CYGWIN

LDFLAGS=


OBJ= \
	coff.o \
	main.o



bin: $(OBJ)
	$(CC) -o $(TARGET) $(LDFLAGS) $(OBJ)


.c.o:
	$(CC) $(CFLAGS) $(CFGFLAGS) -c $< -o $@ 


clean:
	$(RM) $(OBJ) $(TARGET)

